Develop
Sysmap-Microservice/src-ms-sign-portability pull request #24
Opened 2022-02-18 13:44 UTC by Sysmap-Microservice

Code review geral. Todos devem analisar o código como um todo e, caso tudo esteja ok, dar Approve nesse pull request.

2022-02-18 15:45 UTC, andresantossysmap requested changes
Seguem minhas considerações.

2022-02-18 15:45 UTC, andresantossysmap commented on README.md
> +  src-ms-portability:
Alterar para src-ms-sign-portability

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/application/service/SignPortabilityServiceImpl.java
> +                .build();
Sugestão: para evitar muito código dentro do método, criar um método separado para o builder (algo como **portabilityBuilder** ) e fazer a chamada dentro do método **savePortabilityInfo**

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/application/service/SignPortabilityServiceImpl.java
> +    }
Criar uma classe para esta validação

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/application/service/SignPortabilityServiceImpl.java
> +    }
Criar uma classe para os callbacks

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/domain/entities/Portability.java
> +
Remover linhas em branco entre os atributos

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/domain/entities/Portability.java
> +@Document
Remover framework da camada de domain

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/domain/exceptions/CallbackNotFound.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
Remover framework da camada domain

2022-02-18 15:45 UTC, andresantossysmap commented on src/main/java/com/sysmap/srcmssignportability/framework/adapters/in/dto/PortabilityInputKafka.java
> +
Remover linhas em branco entre os atributos

2022-02-18 19:02 UTC, andresantossysmap reviewed
Favor desconsiderar meu comentário sobre as alteraçoes necessárias. Correçoes sendo feitas em outra branch

2022-02-21 13:11 UTC, Riposati approved these changes

2022-02-21 13:25 UTC, julianaSpinaSY approved these changes

2022-02-21 13:58 UTC, andresantossysmap approved these changes

2022-02-21 16:32 UTC, Matheus-Augusto-46 approved these changes
Ok

2022-02-22 13:57 UTC, merged